name: Merging Feature Branch into Develop Branch

on:
  push:
    branches:
      - 'feature**'

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    name: Run Tests & Validate Coverage
    if: ${{ contains(github.event.head_commit.message, 'DEPLOY') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Merge Develop into feature branch
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch:  ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests with coverage
        run: npm run test:cov | tee test-output.txt

      - name: Extract and Validate Coverage
        run: |
          COVERAGE=$(grep -oP '\d+(?=%)' test-output.txt)

          echo "Extracted Coverage: $COVERAGE%"
          if [ "$COVERAGE" -lt 85 ]; then
            echo "Coverage is below 85%! Aborting merge."
            exit 1
          fi

      - name: Coverage Passed
        run: echo "✅ Test coverage is sufficient! Proceeding with merge."

      - name: Merge feature branch into Develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop
